services:
  # ==========================================
  # 1. FRONTEND (Angular 19 - Modo Dev)
  # ==========================================
  frontend:
    image: node:22-alpine
    ports:
      - "4200:4200"
    working_dir: /app/frontend
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --port 4200 --disable-host-check"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - construcheck-network
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - api

  # ==========================================
  # 2. BACKEND (.NET 10 - Modo Dev)
  # ==========================================
  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    ports:
      - "8080:8080"
    working_dir: /app/backend
    command: dotnet watch run --project src/API/API.csproj --urls "http://+:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/app/backend
      - ~/.nuget/packages:/root/.nuget/packages 
    networks:
      - construcheck-network
    depends_on:
      db:
        condition: service_healthy

  # ==========================================
  # 3. BANCO DE DADOS (SQL Server)
  # ==========================================
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - construcheck-network

volumes:
  sqlserver_data:

networks:
  construcheck-network:
    driver: bridge