services:
  # ==========================================
  # 1. APLICATIVO (Front + Back em um só Container)
  # ==========================================
  api:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - construcheck-network

  # ==========================================
  # 2. BANCO DE DADOS (SQL Server)
  # ==========================================
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - construcheck-network

volumes:
  sqlserver_data:

networks:
  construcheck-network:
    driver: bridge