name: CI/CD — Construcheck

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependências
        run: dotnet restore backend/construcheck.slnx

      - name: Build
        run: dotnet build backend/construcheck.slnx --no-restore --configuration Release

      - name: Testes
        run: dotnet test backend/construcheck.slnx --no-build --configuration Release --verbosity normal

  cd:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Azure (Via OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Buscar APENAS a senha do ACR via Azure CLI
        uses: azure/cli@v2
        id: kv_secrets
        with:
          inlineScript: |
            ACR_PWD=$(az keyvault secret show --name "ACR-PASSWORD" --vault-name "construcheckvault" --query value -o tsv)
            echo "::add-mask::$ACR_PWD"
            echo "ACR-PASSWORD=$ACR_PWD" >> $GITHUB_OUTPUT

      - name: Login no Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ steps.kv_secrets.outputs.ACR-PASSWORD }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: 
          file: ./dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/construcheck-api:${{ github.sha }}

      - name: Deploy no Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: construcheck-rg
          containerAppEnvironment: construcheck-env
          containerAppName: construcheck-api
          acrName: ${{ secrets.ACR_NAME }}
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ steps.kv_secrets.outputs.ACR-PASSWORD }} # Usado para o Container Apps baixar a imagem do ACR
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/construcheck-api:${{ github.sha }}
          targetPort: 8080
          secrets: >
            db-password-secret=keyvaultref:https://construcheckvaultfree.vault.azure.net/secrets/DB-PASSWORD/54925a54f1d041928a240209a82771e1
            jwt-secret-secret=keyvaultref:https://construcheckvaultfree.vault.azure.net/secrets/JWT-SECRET/fc3867a1739a4c22a754b7b206d08bfb
            fakecon=keyvaultref:https://construcheckvaultfree.vault.azure.net/secrets/Connection-String/3417db359a114ab294bac79955541a2c
          environmentVariables: >
            ASPNETCORE_ENVIRONMENT=Production
            ASPNETCORE_URLS=http://+:8080
            DB_SERVER=construcheck-sql-server.database.windows.net
            DB_PORT=1433
            DB_NAME=construcheck-db
            DB_USER=construcheck_admin
            DB_PASSWORD=secretref:db-password-secret
            JWT_SECRET=secretref:jwt-secret-secret
            JWT_ISSUER=construcheck-api
            JWT_AUDIENCE=construcheck-client
            JWT_EXPIRATION_MINUTES=60
            CONSTRING=secretref:fakecon
            REFRESH_TOKEN_EXPIRATION_DAYS=7