name: CI/CD — Construcheck

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependências
        run: dotnet restore backend/construcheck.slnx

      - name: Build
        run: dotnet build backend/construcheck.slnx --no-restore --configuration Release

      - name: Testes
        run: dotnet test backend/construcheck.slnx --no-build --configuration Release --verbosity normal

  cd:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    needs: ci  # só roda se o CI passou
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Azure (Via OIDC ou credencial existente)
        uses: azure/login@v2
        with:
          # Exemplo usando OIDC (Recomendado):
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Buscar segredos do Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        id: kv_secrets # ID para referenciar os outputs depois
        with:
          keyvault: "construcheckvault" # Nome do recurso no Azure
          secrets: 'ACR-PASSWORD, DB-PASSWORD, JWT-SECRET' # Lista separada por vírgulas

      - name: Login no Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ steps.kv_secrets.outputs.ACR-PASSWORD }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/construcheck-api:${{ github.sha }}

      # - name: Login no Azure
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: construcheck-rg
          containerAppEnvironment: construcheck-env
          containerAppName: construcheck-api
          acrName: ${{ secrets.ACR_NAME }}
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ steps.kv_secrets.outputs.ACR-PASSWORD }}
          # registryUrl: ${{ secrets.ACR_LOGIN_SERVER }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/construcheck-api:${{ github.sha }}
          targetPort: 8080
          secrets: >
            db-password-secret=keyvaultref:https://construcheckvault.vault.azure.net/secrets/DB-PASSWORD/61aaaf29d5fb41beab6514cda118e63f
            jwt-secret-secret=keyvaultref:https://construcheckvault.vault.azure.net/secrets/JWT-SECRET/148db44880e84d49980d27d676012bb9
          environmentVariables: >
            ASPNETCORE_ENVIRONMENT=Production
            ASPNETCORE_URLS=http://+:8080
            DB_SERVER=construcheck-sql-server.database.windows.net
            DB_PORT=1433
            DB_NAME=construcheck-db
            DB_USER=construcheck_admin
            DB_PASSWORD=secretref:db-password-secret
            JWT_SECRET=secretref:jwt-secret-secret
            JWT_ISSUER=construcheck-api
            JWT_AUDIENCE=construcheck-client
            JWT_EXPIRATION_MINUTES=60